version: '3.1'

services:
    postgresql:
        image: postgres
        container_name: postgres
        environment: 
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=admin
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports: 
            - 5432:5432
        volumes: 
            - data:/var/lib/postgresql/data/pgdata
volumes: 
    data: