version: '3.1'

services:
    mysql:
        image: mysql
        container_name: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=nextlend-crypto
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=123456
        ports: 
            - 3306:3306
        volumes: 
            - data:/var/lib/mysql

    adminer:
        image: adminer
        container_name: mysql-adminer
        ports:
            - 8181:8080
volumes: 
    data:
        